from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs' / 'entregables' / 'Segunda_Entrega_CeroFallas.pdf'
BLUE = colors.HexColor('#123B5D'); TEAL = colors.HexColor('#007C83'); LIGHT = colors.HexColor('#EAF2F5'); GOLD = colors.HexColor('#D99A00'); DARK = colors.HexColor('#202B33'); GRAY = colors.HexColor('#5D6B74')

class NumberedCanvas(canvas.Canvas):
    def __init__(self,*a,**k): super().__init__(*a,**k); self.saved=[]
    def showPage(self): self.saved.append(dict(self.__dict__)); self._startPage()
    def save(self):
        total=len(self.saved)
        for state in self.saved:
            self.__dict__.update(state); self.setFont('Helvetica',8); self.setFillColor(GRAY)
            self.drawString(0.72*inch,0.45*inch,'CeroFallas | Propuesta Conceptual de la Solucion de IT')
            self.drawRightString(7.78*inch,0.45*inch,f'Pagina {self._pageNumber} de {total}')
            super().showPage()
        super().save()

styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='CoverTitle',parent=styles['Title'],fontName='Helvetica-Bold',fontSize=29,leading=34,textColor=BLUE,alignment=TA_CENTER,spaceAfter=14))
styles.add(ParagraphStyle(name='CoverSub',parent=styles['Normal'],fontName='Helvetica',fontSize=14,leading=20,textColor=GRAY,alignment=TA_CENTER))
styles.add(ParagraphStyle(name='H1x',parent=styles['Heading1'],fontName='Helvetica-Bold',fontSize=18,leading=22,textColor=BLUE,spaceBefore=4,spaceAfter=11))
styles.add(ParagraphStyle(name='H2x',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=12.5,leading=16,textColor=TEAL,spaceBefore=10,spaceAfter=6))
styles.add(ParagraphStyle(name='Bodyx',parent=styles['BodyText'],fontName='Helvetica',fontSize=9.4,leading=13,textColor=DARK,spaceAfter=6))
styles.add(ParagraphStyle(name='Small',parent=styles['BodyText'],fontName='Helvetica',fontSize=7.7,leading=9,textColor=DARK))
styles.add(ParagraphStyle(name='Caption',parent=styles['BodyText'],fontName='Helvetica-Oblique',fontSize=8,leading=10,textColor=GRAY,alignment=TA_CENTER,spaceBefore=4,spaceAfter=8))
styles.add(ParagraphStyle(name='HeaderCell',parent=styles['BodyText'],fontName='Helvetica-Bold',fontSize=8.5,leading=10,textColor=colors.white))

def P(text, style='Bodyx'): return Paragraph(text,styles[style])
def heading(text): return P(text,'H1x')
def section(text): return P(text,'H2x')
def bullet(items): return [P('&bull; '+x) for x in items]
def tbl(data,widths,header=True,small=False):
    data=[[P(str(c),'HeaderCell' if header and r==0 else ('Small' if small else 'Bodyx')) for c in row] for r,row in enumerate(data)]
    t=Table(data,colWidths=widths,repeatRows=1 if header else 0,hAlign='LEFT')
    cmds=[('GRID',(0,0),(-1,-1),.35,colors.HexColor('#B7C8D0')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]
    if header: cmds += [('BACKGROUND',(0,0),(-1,0),BLUE),('TEXTCOLOR',(0,0),(-1,0),colors.white)]
    t.setStyle(TableStyle(cmds)); return t
def box(label,sub='',w=150,h=50,color=LIGHT):
    return Table([[P('<b>'+label+'</b><br/><font color="#5D6B74">'+sub+'</font>','Small')]],colWidths=[w],rowHeights=[h],style=TableStyle([('BACKGROUND',(0,0),(-1,-1),color),('BOX',(0,0),(-1,-1),.8,TEAL),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('ALIGN',(0,0),(-1,-1),'CENTER'),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5)]))
def arrow(): return P('<font color="#007C83" size="12">--&gt;</font>','Caption')
def diagram_row(items):
    arr=[]
    for i,item in enumerate(items):
        arr.append(item)
        if i<len(items)-1: arr.append(arrow())
    return Table([arr],colWidths=[x for i in range(len(items)) for x in (1.42*inch, .28*inch)][:len(arr)],hAlign='CENTER',style=TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('ALIGN',(0,0),(-1,-1),'CENTER')]))
def mockup(title, lines, accent=TEAL):
    rows=[[P('<b>'+title+'</b>','Bodyx')]]+[[P(x,'Small')] for x in lines]
    return Table(rows,colWidths=[6.35*inch],style=TableStyle([('BACKGROUND',(0,0),(-1,0),accent),('TEXTCOLOR',(0,0),(-1,0),colors.white),('BOX',(0,0),(-1,-1),.8,BLUE),('INNERGRID',(0,1),(-1,-1),.25,colors.HexColor('#C9D7DD')),('LEFTPADDING',(0,0),(-1,-1),10),('RIGHTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]))

story=[]
story += [Spacer(1,1.25*inch),P('UNIVERSIDAD MARIANO GALVEZ DE GUATEMALA','CoverSub'),Spacer(1,.25*inch),P('CeroFallas','CoverTitle'),P('Propuesta Conceptual de la Solucion de IT<br/>Segunda Entrega - Proyecto de Graduacion II','CoverSub'),Spacer(1,.6*inch),Table([[P('<b>Organizacion:</b> Novafiber Guatemala<br/><b>Proyecto:</b> Gestion inteligente de mantenimiento industrial<br/><b>Complemento innovador:</b> Mantenimiento predictivo con aprendizaje automatico<br/><b>Fecha:</b> Septiembre de 2026','Bodyx')]],colWidths=[4.9*inch],hAlign='CENTER',style=TableStyle([('BACKGROUND',(0,0),(-1,-1),LIGHT),('BOX',(0,0),(-1,-1),1,TEAL),('LEFTPADDING',(0,0),(-1,-1),16),('RIGHTPADDING',(0,0),(-1,-1),16),('TOPPADDING',(0,0),(-1,-1),14),('BOTTOMPADDING',(0,0),(-1,-1),14)])),Spacer(1,.55*inch),P('Documento conceptual elaborado a partir del sistema existente: app web y Android con Firebase, API NestJS y servicio CeroFallasAI.','CoverSub'),PageBreak()]

story += [heading('1. Proposito y alcance'),P('CeroFallas centraliza la gestion de mantenimientos correctivos, preventivos y activos industriales. La mejora propuesta lo convierte en un sistema de soporte a decisiones: cada 24 horas, el modulo analitico estima la probabilidad de falla por equipo en un horizonte de 7 dias y la presenta como semaforo, recomendacion y evidencia para el responsable de mantenimiento.'),section('Alcance funcional'),*bullet(['Registro trazable de correctivos: linea, equipo, turno, falla, responsable, horas y tiempo muerto.','Gestion de planes, ordenes y ejecucion de mantenimientos preventivos.','Indicadores de confiabilidad: MTBF, MTTR, disponibilidad y paros.','Extraccion y preparacion de datos historicos para IA.','Prediccion de riesgo, alertas auditables y exportacion para Power BI.','Operacion paralela: la alerta apoya al jefe de mantenimiento; no crea ni ejecuta una orden automaticamente.']),section('Criterios de exito'),tbl([['Criterio','Evidencia esperada'],['Trazabilidad','Cada evento conserva equipo, fecha, turno, usuario y estado.'],['Utilidad predictiva','Recall, precision, F2 y matriz de confusion comparados contra linea base.'],['Seguridad','Acceso por rol, reglas Firebase, secretos fuera del codigo y bitacora de acciones.'],['Disponibilidad operativa','Riesgo actualizado, fecha de calculo y modelo versionado.']], [1.55*inch,4.8*inch]),PageBreak()]

story += [heading('2. Modelo de datos propuesto'),P('El almacenamiento operacional puede mantenerse en Firebase Realtime Database; este modelo logico normaliza las entidades y relaciones necesarias para asegurar calidad, auditoria e integracion analitica. Las entidades de IA separan la prediccion de la operacion para conservar reproducibilidad.'),section('Entidades principales'),tbl([['Entidad','Atributos clave','Relacion'],['Usuario','id, nombre, correo, rol, estado','Registra ordenes y eventos.'],['LineaProduccion','id, nombre, area, estado','Contiene equipos.'],['Equipo','id, codigo, nombre, criticidad, estado','Pertenece a una linea.'],['PlanPreventivo','id, equipo_id, frecuencia, actividad, activo','Genera ordenes preventivas.'],['OrdenMantenimiento','id, tipo, equipo_id, plan_id?, estado, programada','Puede documentar preventivo o correctivo.'],['EventoCorrectivo','id, orden_id, falla, turno, inicio, fin, minutos','Alimenta indicadores y dataset.'],['PrediccionRiesgo','id, equipo_id, fecha, probabilidad, nivel, modelo','Se consulta en web y Power BI.'],['ModeloML','id, version, algoritmo, metricas, fecha','Origina predicciones.'],['Auditoria','id, usuario_id, accion, entidad, fecha','Rastrea operaciones sensibles.']], [1.35*inch,2.7*inch,2.3*inch],small=True),section('Relaciones clave'),diagram_row([box('LINEA','1',90,42),box('EQUIPO','N',90,42),box('ORDEN','N',90,42),box('EVENTO','0..N',90,42),box('RIESGO','0..N',90,42)]),P('Linea 1:N Equipo; Equipo 1:N Orden; Orden 1:0..N Evento; Equipo 1:N PrediccionRiesgo. PlanPreventivo 1:N Orden y ModeloML 1:N PrediccionRiesgo.','Caption'),PageBreak()]

story += [heading('3. Diagramas de procesos'),section('3.1 Proceso general'),diagram_row([box('Captura','Correctivos y preventivos',105,55),box('Persistencia','Firebase / historico',105,55),box('Analitica','ETL + variables',105,55),box('Decision','Riesgo y alerta',105,55)]),P('El ciclo es continuo: las acciones humanas generan datos; los datos se validan y se convierten en indicadores y riesgo; el jefe de mantenimiento valida la recomendacion y define la intervencion.'),section('3.2 Registro de correctivo'),tbl([['Paso','Responsable','Control de calidad'],['1. Reporta anomalia','Operador o tecnico','Equipo y linea obligatorios.'],['2. Crea orden correctiva','Tecnico','Estado: abierta; fecha/hora auditables.'],['3. Diagnostica y repara','Tecnico','Causa, falla, inicio/fin y repuestos.'],['4. Valida cierre','Jefe de mantenimiento','Minutos no negativos; cierre autorizado.'],['5. Actualiza KPI/dataset','Sistema','Evento disponible para MTTR, MTBF e IA.']], [1.2*inch,1.55*inch,3.6*inch]),section('3.3 Proceso predictivo programado'),diagram_row([box('Extraer','Historico validado',100,48),box('Transformar','Ventanas 7/15/30/60',100,48),box('Inferir','Modelo aprobado',100,48),box('Publicar','Riesgo + Power BI',100,48)]),*bullet(['Se bloquea la publicacion si faltan campos criticos, el modelo no esta aprobado o la ejecucion falla.','Las predicciones guardan fecha, version de modelo y variables utilizadas para auditoria.','El reentrenamiento requiere evaluacion y aprobacion; no debe reemplazar un modelo productivo de manera automatica.']),PageBreak()]

story += [heading('4. Casos de uso y permisos'),P('Se recomienda implementar RBAC (control de acceso basado en roles). El sistema actual debe pasar de autenticacion solamente a autorizacion por accion y por linea asignada.'),tbl([['Actor','Casos de uso permitidos','Restricciones'],['Administrador','Gestionar usuarios, roles, catalogos, equipos y configuracion','No altera resultados historicos sin auditoria.'],['Jefe de mantenimiento','Consultar KPIs/riesgo, aprobar ordenes y cierre, programar preventivos','Puede decidir sobre alertas; no modifica metricas de modelo.'],['Tecnico','Registrar correctivo, ejecutar orden, adjuntar evidencia, consultar tareas','Solo sus ordenes o lineas autorizadas.'],['Operador','Reportar anomalia y consultar estado','No cierra ordenes ni ve configuracion de IA.'],['Analista IA','Extraer, preparar, entrenar, evaluar y proponer modelo','No accede a datos personales innecesarios; publicacion aprobada.'],['Power BI','Leer vista de integracion de solo lectura','Sin privilegio de escritura operacional.']], [1.2*inch,3.25*inch,1.9*inch],small=True),section('Casos de uso prioritarios para mockups'),*bullet(['UC-01: iniciar sesion y recibir menu segun rol.','UC-02: registrar y cerrar mantenimiento correctivo.','UC-03: programar y marcar mantenimiento preventivo.','UC-04: consultar riesgo por equipo y confirmar accion operativa.','UC-05: revisar metricas, comparativa de modelos e impacto economico.']),PageBreak()]

story += [heading('5. Arquitectura de software'),P('La arquitectura propuesta conserva las plataformas existentes y agrega una capa de IA desacoplada. Esto permite validar el valor predictivo sin poner en riesgo la operacion transaccional.'),section('Componentes'),diagram_row([box('Usuarios','Web / Android',100,55),box('Aplicacion','Angular / Android',110,55),box('Servicios','Firebase + API NestJS',120,55),box('IA','Python / scikit-learn',105,55)]),Spacer(1,10),diagram_row([box('Planificador','Cada 24 h',105,48),box('Integracion','Vista/CSV protegida',115,48),box('Power BI','Dashboard ejecutivo',105,48)]),section('Responsabilidades y controles'),tbl([['Capa','Responsabilidad','Control'],['Cliente','Captura y consulta','Validacion de formularios, sesion, menu por rol.'],['Datos operativos','Fuente de verdad','Reglas Firebase, indice por fecha/equipo, respaldos.'],['API','Contratos e integracion','JWT, validacion DTO, rate limit, logs y Swagger restringido.'],['IA','Dataset, entrenamiento e inferencia','Versionado, validacion temporal, umbral aprobado.'],['BI','Visualizacion','Conector de solo lectura y datos minimizados.']], [1.2*inch,2.75*inch,2.4*inch],small=True),PageBreak()]

story += [heading('6. Mockups de casos de uso'),section('6.1 Dashboard de mantenimiento'),mockup('CeroFallas | Dashboard', ['[Menu] Inicio  Correctivos  Preventivos  Confiabilidad  Riesgo IA','KPIs: Disponibilidad 92.4% | MTBF 168 h | MTTR 3.1 h | Preventivos al dia 86%','Alertas IA: 2 equipos CRITICOS | 4 en MONITOREO | Ultima actualizacion: 02/09/2026 06:00','[Grafica] Paros por linea y tendencia de fallas | [Accion] Ver equipos con riesgo']),P('El dashboard prioriza decisiones: los indicadores y la fecha de actualizacion deben ser visibles; no se muestra una prediccion como certeza.' ,'Caption'),section('6.2 Registro de correctivo'),mockup('Nueva orden correctiva', ['Equipo * [Selector]   Linea * [Selector]   Turno * [Selector]','Falla * [Catalogo]  Descripcion [Texto]  Prioridad [Media/Alta/Critica]','Inicio * [Fecha/Hora]  Fin [Fecha/Hora]  Minutos [Calculado]','[Guardar borrador]   [Enviar para cierre]   Evidencia [Adjuntar]'],GOLD),P('Validaciones: campos obligatorios, hora final posterior al inicio, catalogo de falla, usuario autenticado y registro de auditoria.','Caption'),section('6.3 Riesgo predictivo'),mockup('Riesgo predictivo por equipo', ['Filtros: Linea [Todas] | Nivel [Critico] | Fecha de calculo [02/09/2026]','EQUIPO: PRENSA L2 | Riesgo 78% | SEMAFORO ROJO | Horizonte: 7 dias','Factores: 3 fallas en 30 dias; 41 dias sin preventivo; 390 min de paro','Recomendacion: Inspeccionar sistema hidraulico y programar OT. [Crear OT] [Marcar revisado]','Trazabilidad: Modelo v1.0 | Ejecutado 06:00 | Estado: pendiente de decision']),PageBreak()]

story += [heading('7. Estrategia de datos y validacion de IA'),section('Variables predictoras'),tbl([['Grupo','Variables propuestas'],['Temporal','Dias desde ultimo preventivo, dias desde ultima falla, mes, dia de semana, turno.'],['Frecuencia','Fallas y minutos de paro en ventanas de 7, 15, 30 y 60 dias.'],['Contexto','Linea, equipo, criticidad, tipo de falla y causa recurrente.'],['Objetivo','Falla real del equipo dentro de los proximos 7 dias (si/no).']], [1.25*inch,5.1*inch]),section('Protocolo de validacion'),*bullet(['Separar datos por tiempo: nunca usar eventos futuros para predecir el pasado.','Comparar regresion logistica como linea base interpretable contra un modelo de mayor capacidad (p. ej. Random Forest) solo si hay suficiente historial.','Aplicar validacion cruzada temporal o por bloques, no mezcla aleatoria simple.','Evaluar precision, recall, F2, ROC-AUC, matriz de confusion y costo de falsos negativos.','Seleccionar umbral por costo operativo y capacidad diaria de inspeccion; documentar la decision.']),section('Limitaciones declaradas'),P('La prediccion depende de datos completos y consistentes. Con poco historial o cambios de proceso, el resultado debe etiquetarse como exploratorio y requerir validacion humana. El sistema no diagnostica una causa fisica ni reemplaza la inspeccion tecnica.'),PageBreak()]

story += [heading('8. Calidad, seguridad y plan de implementacion'),section('Hallazgos de analisis y seguridad'),tbl([['Hallazgo','Riesgo','Accion definida'],['Credencial Firebase en codigo','Exposicion al publicar Git','Se sustituyo por variables de entorno y .env.example. Rotar la clave original antes de despliegue.'],['Sin RBAC comprobable','Acceso excesivo a operaciones','Implementar roles, reglas Firebase y autorizacion en API.'],['Pipeline invocable por API','Uso no autorizado / consumo','Restringir a administrador, autenticar y registrar ejecuciones.'],['Datos de mantenimiento sensibles','Divulgacion operacional','No versionar datasets ni reportes productivos; minimizar datos en BI.'],['Calidad de datos','Prediccion sesgada o invalida','Reglas de validacion, catalogos y monitoreo de campos nulos.']], [1.6*inch,2.0*inch,2.75*inch],small=True),section('Plan de QA'),*bullet(['Pruebas unitarias: calculo de minutos, validaciones DTO, variables y umbrales.','Pruebas de integracion: Firebase/API, ejecucion programada, exportacion Power BI y permisos.','Pruebas de aceptacion: tecnico registra, jefe aprueba, alerta se revisa y queda auditada.','Pruebas de seguridad: acceso denegado por rol, secretos ausentes de Git, entradas invalidas y registro de acciones.','Criterio de salida: flujo critico sin defectos bloqueantes, trazabilidad demostrable y resultado IA reproducible.']),section('Ruta de trabajo inmediata'),tbl([['Fase','Entregable'],['1. Base segura','Monorepo, .gitignore, secretos fuera de Git y primer commit.'],['2. Diseno','Validar modelo, procesos y mockups con asesor/usuarios.'],['3. Desarrollo','RBAC, entidades faltantes y persistencia trazable.'],['4. IA','Dataset anonimo, experimento reproducible, comparacion y umbral.'],['5. Operacion','Programacion 24 h, Power BI, QA, documentacion y defensa.']], [1.25*inch,5.1*inch]),Spacer(1,14),P('Conclusion: CeroFallas se presenta como un DSS de mantenimiento. La innovacion defendible no es solo usar un algoritmo, sino integrar datos confiables, validacion cientifica, alertas auditables, seguridad por roles y decisiones humanas medibles.','Bodyx')]

OUT.parent.mkdir(parents=True,exist_ok=True)
doc=SimpleDocTemplate(str(OUT),pagesize=letter,leftMargin=.72*inch,rightMargin=.72*inch,topMargin=.65*inch,bottomMargin=.68*inch,title='Segunda Entrega - CeroFallas')
doc.build(story,canvasmaker=NumberedCanvas)
print(OUT)
